Repository WildCodeSchool/2023-03-remote-fr-php-afac-974, pull requests merged in 2023-07, with the labels that each got.

#68 Page 403
  templates/bundles/TwigBundle/Exception/error403.html.twig
Labels: request_changed

#70 Ajout de Chart.js et du graphique des paintings les plus envoyées
  assets/app.js
  assets/controllers.json
  assets/styles/_admin.scss
  composer.json
  composer.lock
  config/bundles.php
  package.json
  src/Controller/AdminController.php
  symfony.lock
  templates/admin/index.html.twig
  yarn.lock
Labels: ok

#72 changement des titres des pageswÃ
  templates/admin/index.html.twig
  templates/admin_artist/edit.html.twig
  templates/admin_artist/index.html.twig
  templates/admin_artist/new.html.twig
  templates/admin_category/index.html.twig
  templates/admin_painting/edit.html.twig
  templates/admin_painting/index.html.twig
  templates/admin_user/edit.html.twig
  templates/admin_user/index.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: ok

#105 Us/rand painting
  assets/styles/_galery.scss
  assets/styles/_painting.scss
  config/packages/doctrine.yaml
  src/Bundle/Dql.php
  src/Controller/PaintingController.php
  src/Entity/Ecard.php
  src/Repository/PaintingRepository.php
  templates/base.html.twig
  templates/galery/index.html.twig
  templates/painting/random.html.twig
Labels: request_changed

#114 Changement balise navbar
  templates/include/_footer.html.twig
  templates/include/_navbar.html.twig
  templates/painting/show.html.twig
Labels: ok

#115 Fix texte
  templates/painting/show.html.twig
Labels: conflit
